<?php

	//application details
		$apps[$x]['name'] = 'Billing';
		$apps[$x]['uuid'] = 'b2c3d4e5-f6a7-8901-bcde-f12345678901';
		$apps[$x]['category'] = 'Admin';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '1.0.0';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = '';
		$apps[$x]['description']['en-us'] = 'Mini Billing System for domain subscriptions with payment gateway integration (PayPal, Stripe, Binance Pay).';

	//permission details
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = 'billing_dashboard_view';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = 'b2c3d4e5-0001-0001-0001-000000000001';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_plan_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_plans_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_plans_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_plans_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_subscription_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_subscriptions_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_subscriptions_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_subscriptions_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_invoice_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_invoices_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_invoices_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_invoice_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_payment_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_payments_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_payments_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_payment_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_notice_template_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_notice_templates_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_notice_templates_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_notice_templates_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_gateway_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_payment_gateways_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_payment_gateways_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_payment_gateways_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_credit_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_credits_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_credit_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_credit_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'billing_pay_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'admin';

	//default settings
		$y = 0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'b2c3d4e5-0002-0001-0001-000000000001';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'billing';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'currency';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'text';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = 'USD';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Default billing currency.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'b2c3d4e5-0002-0001-0001-000000000002';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'billing';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'tax_rate';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '0';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Tax rate percentage applied to invoices.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'b2c3d4e5-0002-0001-0001-000000000003';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'billing';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'invoice_prefix';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'text';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = 'INV-';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Invoice number prefix.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'b2c3d4e5-0002-0001-0001-000000000004';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'billing';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'grace_period_days';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '7';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Number of days after expiration before domain suspension.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'b2c3d4e5-0002-0001-0001-000000000005';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'billing';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'auto_suspend';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'boolean';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Automatically suspend domains when subscription expires.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'b2c3d4e5-0002-0001-0001-000000000006';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'billing';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'company_name';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'text';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Company name for invoices.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'b2c3d4e5-0002-0001-0001-000000000007';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'billing';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'company_address';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'text';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Company address for invoices.';

	//schema details - billing_plans
		$y = 0;
		$apps[$x]['db'][$y]['table']['name'] = 'v_billing_plans';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'plan_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Plan UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'plan_name';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Plan name';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'description';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Plan description';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'price';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(10,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Plan price';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'currency';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Currency code';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'billing_cycle';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Billing cycle (monthly/quarterly/yearly)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_extensions';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum extensions allowed';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_gateways';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum gateways allowed';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_ivrs';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum IVRs allowed';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_call_recordings';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum call recordings allowed';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_ring_groups';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum ring groups allowed';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'features_json';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Additional features in JSON format';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'enabled';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enabled status';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who added the plan';

	//schema details - billing_subscriptions
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'v_billing_subscriptions';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'subscription_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Subscription UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'foreign';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = 'v_domains';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'plan_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Plan UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller UUID (nullable)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'status';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Subscription status';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'start_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Subscription start date';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'end_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Subscription end date';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'next_billing_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Next billing date';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'auto_renew';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Auto renew enabled';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'trial_ends_at';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Trial end date';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'mod_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date modified';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'mod_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who modified';

	//schema details - billing_invoices
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'v_billing_invoices';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'invoice_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Invoice UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'subscription_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Subscription UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'invoice_number';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(64)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Invoice number';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'amount';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(10,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Invoice amount';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'currency';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Currency code';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'tax_amount';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(10,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Tax amount';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'total_amount';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(10,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Total amount';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'status';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Invoice status';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'due_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Due date';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'paid_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Paid date';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'payment_method';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(64)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Payment method used';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'payment_reference';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Payment reference';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'pdf_path';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(512)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'PDF file path';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';

	//schema details - billing_payments
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'v_billing_payments';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'payment_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Payment UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'invoice_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Invoice UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'amount';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(10,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Payment amount';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'currency';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Currency code';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'payment_gateway';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Payment gateway used';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'transaction_id';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Gateway transaction ID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'status';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Payment status';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'gateway_response_json';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Gateway response JSON';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';

	//schema details - billing_notices
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'v_billing_notices';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'notice_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Notice UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'subscription_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Subscription UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'notice_type';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(64)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Notice type';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'sent_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date sent';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'sent_to';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Recipient';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'sent_via';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(16)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Delivery method (email/sms)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_used';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Template used';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'status';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(16)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Delivery status';

	//schema details - billing_notice_templates
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'v_billing_notice_templates';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Template UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_name';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Template name';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'notice_type';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(64)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Notice type';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'subject';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(512)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Email subject';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'body_html';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'HTML body';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'body_text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Plain text body';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'variables_json';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Available variables JSON';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'enabled';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enabled status';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';

	//schema details - billing_payment_gateways
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'v_billing_payment_gateways';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'gateway_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Gateway UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'gateway_name';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Gateway name (paypal/stripe/binance)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'display_name';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(128)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Display name';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'api_key_encrypted';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Encrypted API key';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'api_secret_encrypted';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Encrypted API secret';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'webhook_secret';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Webhook secret';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'sandbox_mode';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Sandbox mode enabled';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'enabled';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enabled status';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'config_json';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Additional config JSON';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';

	//schema details - billing_credits
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'v_billing_credits';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'credit_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Credit UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'amount';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(10,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Credit amount';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'currency';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Currency code';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'description';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Credit description';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'transaction_type';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(16)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Transaction type (credit/debit)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reference_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reference UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who added';

?>
