<?php

	//application details
		$apps[$x]['name'] = 'Domain Wizard';
		$apps[$x]['uuid'] = '6e1d4a7c-2b8f-4e3d-9c5a-1d7b0e6f3a2c';
		$apps[$x]['category'] = 'Admin';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '1.0.0';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = '';
		$apps[$x]['description']['en-us'] = 'Domain Creation Wizard that allows admins to easily clone a demo domain with configurable options.';

	//permission details
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = 'domain_wizard_view';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = '6e1d4a7c-2b8f-4e3d-9c5a-1d7b0e6f3a2d';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'domain_wizard_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'domain_wizard_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'domain_wizard_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';

	//default settings
		$y = 0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-a7b8-9012-cdef-123456789012';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'domain_wizard';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'max_extensions';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '100';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Maximum number of extensions to clone per domain.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-a7b8-9012-cdef-123456789013';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'domain_wizard';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'max_gateways';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '10';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Maximum number of gateways to clone per domain.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-a7b8-9012-cdef-123456789014';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'domain_wizard';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'max_ivrs';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '10';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Maximum number of IVRs to clone per domain.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-a7b8-9012-cdef-123456789015';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'domain_wizard';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'max_ring_groups';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '10';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Maximum number of ring groups to clone per domain.';

	//schema details - domain_wizard_templates
		$y = 0;
		$apps[$x]['db'][$y]['table']['name'] = 'domain_wizard_templates';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_wizard_template_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Template UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_name';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Template name';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'source_domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Source domain UUID to clone from';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'default_extensions';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Default number of extensions';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'default_gateways';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Default number of gateways';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'default_ivrs';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Default number of IVRs';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'default_ring_groups';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Default number of ring groups';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'description';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Template description';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'enabled';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enabled status';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who added the template';

	//schema details - domain_wizard_logs
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'domain_wizard_logs';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_wizard_log_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Log UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Created domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Template UUID used';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'created_by';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who created the domain';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'extensions_count';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Number of extensions created';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'gateways_count';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Number of gateways created';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'ivrs_count';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Number of IVRs created';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'recordings_uploaded';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Number of recordings uploaded';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'status';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Status of the operation';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'log_detail';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Detailed log information';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';

?>
