<?php

	//application details
		$apps[$x]['name'] = 'Reseller';
		$apps[$x]['uuid'] = 'c3d4e5f6-a7b8-9012-cdef-123456789012';
		$apps[$x]['category'] = 'Admin';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '1.0.0';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = '';
		$apps[$x]['description']['en-us'] = 'Reseller Support allowing resellers to manage domains according to their privileges and subscription.';

	//permission details
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_view';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = 'c3d40001-a7b8-9012-cdef-123456789012';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_profile_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_profile_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_all';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_dashboard';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = 'c3d40002-a7b8-9012-cdef-123456789012';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_domains_view';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = 'c3d40003-a7b8-9012-cdef-123456789012';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_domain_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_domains_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_domains_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_plans_view';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = 'c3d40004-a7b8-9012-cdef-123456789012';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_plan_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_plan_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_plans_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_commissions_view';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = 'c3d40005-a7b8-9012-cdef-123456789012';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_activity_view';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = 'c3d40006-a7b8-9012-cdef-123456789012';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_settings_view';
		$apps[$x]['permissions'][$y]['menu']['uuid'] = 'c3d40007-a7b8-9012-cdef-123456789012';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_profile_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_api_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_portal_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';

	//default settings
		$y = 0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-0001-9012-cdef-123456789012';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'reseller';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'max_domains_default';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '50';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Default maximum domains a new reseller can create.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-0002-9012-cdef-123456789012';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'reseller';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'max_extensions_default';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '500';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Default maximum total extensions across all reseller domains.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-0003-9012-cdef-123456789012';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'reseller';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'max_gateways_default';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '50';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Default maximum total gateways across all reseller domains.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-0004-9012-cdef-123456789012';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'reseller';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'default_commission_rate';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '10';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Default commission rate percentage for new resellers.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-0005-9012-cdef-123456789012';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'reseller';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'api_rate_limit';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'numeric';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = '60';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Maximum API requests per minute per reseller.';
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = 'c3d4e5f6-0006-9012-cdef-123456789012';
		$apps[$x]['default_settings'][$y]['default_setting_category'] = 'reseller';
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = 'currency';
		$apps[$x]['default_settings'][$y]['default_setting_name'] = 'text';
		$apps[$x]['default_settings'][$y]['default_setting_value'] = 'USD';
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = 'true';
		$apps[$x]['default_settings'][$y]['default_setting_description'] = 'Default currency for reseller commissions.';

	//schema details - v_reseller_profiles
		$y = 0;
		$apps[$x]['db'][$y]['table']['name'] = 'reseller_profiles';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'user_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Associated user UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller own domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'company_name';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Company name';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'contact_name';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Contact name';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'contact_email';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Contact email';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'contact_phone';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Contact phone';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'address';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Physical address';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'tax_id';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(64)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Tax identification number';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'commission_rate';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(5,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Commission rate percentage';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'status';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Status (active/suspended/pending)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_domains';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum domains allowed';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_total_extensions';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum total extensions across all domains';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_total_gateways';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum total gateways across all domains';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'allowed_features_json';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'JSON array of allowed features';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'branding_json';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'JSON branding config (logo_url, company_name, support_email, support_phone)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'api_key';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(128)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'API key';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'api_secret';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'API secret (hashed)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'notes';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Notes';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'enabled';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enabled';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'mod_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date modified';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'mod_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who modified';

	//schema details - v_reseller_domains
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'reseller_domains';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller domain mapping UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'foreign';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = 'v_reseller_profiles';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Managed domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'subscription_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Billing subscription UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'status';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Domain status';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'provisioned_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date domain was provisioned';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'notes';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Notes';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who added';

	//schema details - v_reseller_plans
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'reseller_plans';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_plan_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller plan UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'foreign';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = 'v_reseller_profiles';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'plan_name';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(255)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Plan name';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'description';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Plan description';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'base_plan_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Base billing plan UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'markup_amount';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(10,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Markup amount';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'markup_type';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(16)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Markup type (fixed/percentage)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_extensions';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Max extensions per domain on this plan';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_gateways';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Max gateways per domain on this plan';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_ivrs';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Max IVRs per domain on this plan';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'features_json';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'JSON features included in plan';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'enabled';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enabled';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who added';

	//schema details - v_reseller_commissions
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'reseller_commissions';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'commission_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Commission UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'foreign';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = 'v_reseller_profiles';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'payment_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Billing payment UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Domain UUID the commission is for';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'amount';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'real';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'decimal(10,2)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Commission amount';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'currency';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Currency code';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'status';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(32)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Status (pending/paid/cancelled)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'paid_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date commission was paid';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';

	//schema details - v_reseller_activity_log
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'reseller_activity_log';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'log_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Log entry UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'foreign';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = 'v_reseller_profiles';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Related domain UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'action';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(64)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Action performed';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'details_json';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'JSON details of the action';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'ip_address';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(45)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'IP address';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';

	//schema details - v_reseller_permissions
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = 'reseller_permissions';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'permission_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Permission UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'foreign';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = 'v_reseller_profiles';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = 'reseller_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Reseller UUID';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'resource_type';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(64)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Resource type (extensions/gateways/ivrs/ring_groups/recordings/users/dialplan)';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'can_view';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Can view';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'can_add';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Can add';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'can_edit';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Can edit';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'can_delete';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'varchar(8)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Can delete';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'max_count';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'numeric';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'integer';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'int';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Maximum count for resource';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'timestamptz';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'date';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'datetime';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Date added';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'add_user';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'User who added';

?>
