<?php

	//admin permissions - manage all resellers
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_profile_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_profile_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_all';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';

	//reseller permissions - manage own domains within limits
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_dashboard';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_domains_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_domain_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_domains_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_domains_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_plans_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_plan_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_plan_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_plans_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_commissions_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_activity_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_settings_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_profile_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_api_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'reseller_portal_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		$apps[$x]['permissions'][$y]['groups'][] = 'reseller';

?>
